const express=require('express')
const app=express()
app.set('view engine', 'ejs')
app.use(express.static('Script'))
app.use(express.static('Style'))
app.use(express.static('Images'))
app.get("/",(req,res)=>{
    res.render('index')
})
app.listen(3000)